### PR TITLE
148 bulk get

### PR DESCRIPTION
**Pull request by qpfiffer**
Good checkpoint for this. Adds a `_bulk_unjar` endpoint to the HTTP frontend that allows one to access values in the database.

Code review pls @Hamcha @Xe, I wrote a chunk of the Go code last night with @kyleterry and I wrote the C stuff a couple of weeks ago.

Edit: I should also note that this will work great for simple string values stored in Oleg (like JSON or some shit) but will fall over on binary data because the `ol_bulk_unjar` function returns null terminated strings and not size/value pairs. I'll have to rewrite it before it's out the door but for now I just want some eyes to make sure what is there is alright.

### CODE REVIEW

**Comment by kyleterry** [comment]
:+1: looks good if the CI returns successfully.

**Comment by dequis** [comment]
@qpfiffer 1c802c5d381c9e3aff99c6801123bbc4304cf507

**Comment by qpfiffer** [comment]
:package:

**Comment by Xe** [comment]
:package:

**Comment by dequis** [comment]
:package:

**Comment by qpfiffer** [comment]
ITS NOT DONE THERE ARE MEMORY LEAKS YOU FRENCH-HORNS

**Comment by colby** [comment]
@qpfiffer Please fix memory leaks, this code is not ready for a merge.

**Comment by dequis** [comment]
@qpfiffer :package:

**Comment by lykkin** [comment]
@qpfiffer :shipit:

**Comment by qpfiffer** [comment]
STIP PINGING ME :finnadie:

**Comment by Xe** [comment]
@qpfiffer :1234:

**Comment by qpfiffer** [comment]
Fuck it, there are memory leaks on master too, in the Golang unjar stuff. I dunno what the hell is up with that. INTO THE FLAMES IT GOES.

**Pull request merged**
