### PR TITLE
async.c - Authentic Shitposting General

### PR DESCRIPTION
**Pull request by PrestonSmith01**
Allows transaction to run asynchronously increasing speed and organizes
each transaction from largest to smallest via Big O Notation

### CODE REVIEW

**Comment by qpfiffer** [comment]
:performing_arts: :sandal: :ice_cream: :ocean:

**Comment by dequis** [comment]
:package:

**Comment by benwaffle** [comment]
ack

**Comment by qpfiffer** [comment]
:point_right: :finnadie: :point_right: 
:hammer: :non-potable_water: :money_with_wings: 
    :eggplant: 
:poultry_leg: :poultry_leg:

**Comment by dequis** [comment]
:white_medium_square: :white_medium_square: :white_medium_square: :package: :package: :package: :package: :package: 
:white_medium_square: :white_medium_square: :package: :white_medium_square: :white_medium_square: :white_medium_square: :package: :package: 
:white_medium_square: :package: :white_medium_square: :white_medium_square: :white_medium_square: :package: :white_medium_square: :package: 
:package: :package: :package: :package: :package: :white_medium_square: :white_medium_square: :package: 
:package: :white_medium_square: :white_medium_square: :white_medium_square: :package: :white_medium_square: :white_medium_square: :package: 
:package: :white_medium_square: :white_medium_square: :white_medium_square: :package: :white_medium_square: :package: :white_medium_square: 
:package: :white_medium_square: :white_medium_square: :white_medium_square: :package: :package: :white_medium_square: :white_medium_square: 
:package: :package: :package: :package: :package: :white_medium_square: :white_medium_square: :white_medium_square:

**Comment by dequis** [comment]
Thank you for your report. Unfortunately, I was unable to reproduce your issue. Closing ticket as 'works for me'.

**Comment by dequis** [comment]
:package:

**Comment by Xe** [comment]
oh you guys

**Comment by lykkin** [comment]
this pr is oppressing my freedoms

**Comment by Xe** [comment]
Code LGTM, please merge this as it passes travis CI tests

**Comment by Hamcha** [comment]
The correct capitalization is OlegDB, not Olegdb.
Also, you haven't applied @dequis corrections. I don't think this is ready to merge just yet.

But the worst thing is that I don't see the point of it.
Obviously this should be Front-end code, @kyleterry do you think porting this to our current Go frontend would be easy enough?

**Comment by Xe** [comment]
will

```php
<?php
echo('                                                                                        
                                      legDBOleg                                         
                                  DBOlegDBOlegDBOle                                     
                              gDBOlegDBOlegDBOlegDBOle                                  
                      gDBOlegDBOlegDB           OlegDBOl                                
                   egDBOlegDBOle                  gDBOleg                               
                 DBOlegDBOlegDBO                   legDBO                               
                 legDBOlegDBOlegD                   BOleg                               
                 DBOlegDBOle gDBOle    gDBOlegDBOl  egDBO                               
                 legDBOlegDBOlegDBOl egDBOlegDBOlegD BOle                               
                 gDBOlegDBOlegDBOl  egDBOlegDBOlegDBOlegD                               
                BOleg  DBOlegDBOle  gDBOlegDBOlegDBOlegDB                               
               OlegDBOlegDBOlegDBOl egDBOlegDBO legDBOleg                               
              DBOlegDBOlegDBOlegD   BOlegDBOlegDBOlegDBOl                               
             egDBOlegDBOlegDBOlegDBOlegDBOlegDBOl  egDBO                                
            legDB          OlegDBOlegDBOlegDB     OlegDB                                
           OlegD                      BOlegDB     OlegDB                                
          OlegDB                                 OlegDB                                 
         OlegDB                                 OlegDB                                  
        OlegDB                                  OlegDB                                  
        OlegD                      BOle        gDBOle                                   
        gDBO                      legDB Ole   gDBOle                                    
        gDBO                      legDBOlegD  BOleg                         DBOlegDBO   
       legDB                      OlegDBOle  gDBOl                        egDBOlegDBOl  
       egDBO                     legDBOlegD BOleg                       DBOleg    DBOl  
       egDBO                     legDBOleg  DBOle                     gDBOleg    DBOle  
       gDBOl                    egDBOlegD  BOlegD                   BOlegDB     OlegD   
       BOleg                    DBOlegDB   OlegDBOlegDBOlegDBOl   egDBOle     gDBOl     
        egDB                   OlegDBOl    egDBOlegDBOlegDBOlegDBOlegDB      OlegD      
        BOle                   gDBOleg     DBOle   gDBOl   egDBOlegDB      OlegDB       
        Oleg                  DBOlegDB      Ole   gDBOlegDBOlegDBOl      egDBOl         
        egDBO               legDB OlegD         BOlegDBOlegDBOlegD     BOlegDB          
         Oleg             DBOle  gDBOleg         DBOlegDBOlegDBOlegD   BOlegDBO         
         legDB            OlegDBOlegDBOl                     egDBOleg    DBOlegDBO      
          legDB            OlegDBOlegDB              Oleg       DBOleg  DBOl egDBO      
          legDBO              legD                   BOle        gDBOle  gDBOlegD       
           BOlegD                                BOl              egDBO    legD         
            BOlegDBO                            legD              BOleg     DBOl        
               egDBOle                          gDBO              legDBOlegDBOle        
     gDB        OlegDBOleg                       DBOl           egDBOlegDBOlegD         
    BOlegDB    OlegDBOlegDBOlegD                  BOl         egDBOle    g              
    DBOlegDBOlegDB OlegDBOlegDBOlegDBOle           gDBO    legDBOl                      
    egDB OlegDBOlegDBOl    egDBOlegDBOlegD BOlegDBOlegDBOlegDBOl                        
     egDB  OlegDBOleg         DBOlegDBOle gDBOlegDBOlegDBOleg                           
      DBOl   egDBOl         egDBOlegDBOl egDBO legDBOlegDB                              
       OlegDBOleg           DBOlegDBOle  gDBO                                           
        legDBOl              egDBOleg   DBOl                                            
          egD                BOlegD    BOle                                             
                              gDBOle  gDBO                                              
                               legDBOlegD                                               
                                 BOlegDB                                                
                                   Ole');
```

suffice as a replacement? PHP is web scale and C is not.

**Comment by Xe** [comment]
Hold on I am an idiot. If this is PHP:

```php
<?php

/**
 * Base Oleg Async Exception because apparently one-file one-function libraries need them.
 */
class OlegAsyncBaseException extends Exception {};
/**
 * Exception but with details. Takes and holds a code and a message.
 * If you make code anything but a number and message anything but a string you deserve whatever breaks.
 */
class OlegAsyncDetailedException extends OlegAsyncBaseException {
	public $code;
	public $message;
	public function __construct($code, $message) {
		$this->code = $code;
		$this->message = $message;
	}
};
/**
 * Thrown if we have no hostname to use. You need to have http as part of it or things will break.
 */
class OlegAsyncNoHostException extends OlegAsyncBaseException {};
/**
 * Thrown if we have no API key.
 */
class OlegAsyncNoAPIKeyException extends OlegAsyncBaseException {};
/**
 * Thrown if OlegDB's awesome async layer says it doesn't know that network.
 */
class OlegAsyncNoSuchNetworkException extends OlegAsyncBaseException {};
/**
 * Thrown if some real weird crap happened.
 */
class OlegAsyncSomeRealWeirdCrapHappenedException extends OlegAsyncBaseException {};

/**
 * Thrown if some real weird crap happened and the user wants details.
 * What is this, 1998 now? We need to give users information? Commies.
 */
class OlegAsyncSomeRealWeirdCrapHappenedAndTheUserWantsDetailedInformationForSomeReasonException extends OlegAsyncDetailedException {};
?>
                                                                                        
                                      legDBOleg                                         
                                  DBOlegDBOlegDBOle                                     
                              gDBOlegDBOlegDBOlegDBOle                                  
                      gDBOlegDBOlegDB           OlegDBOl                                
                   egDBOlegDBOle                  gDBOleg                               
                 DBOlegDBOlegDBO                   legDBO                               
                 legDBOlegDBOlegD                   BOleg                               
                 DBOlegDBOle gDBOle    gDBOlegDBOl  egDBO                               
                 legDBOlegDBOlegDBOl egDBOlegDBOlegD BOle                               
                 gDBOlegDBOlegDBOl  egDBOlegDBOlegDBOlegD                               
                BOleg  DBOlegDBOle  gDBOlegDBOlegDBOlegDB                               
               OlegDBOlegDBOlegDBOl egDBOlegDBO legDBOleg                               
              DBOlegDBOlegDBOlegD   BOlegDBOlegDBOlegDBOl                               
             egDBOlegDBOlegDBOlegDBOlegDBOlegDBOl  egDBO                                
            legDB          OlegDBOlegDBOlegDB     OlegDB                                
           OlegD                      BOlegDB     OlegDB                                
          OlegDB                                 OlegDB                                 
         OlegDB                                 OlegDB                                  
        OlegDB                                  OlegDB                                  
        OlegD                      BOle        gDBOle                                   
        gDBO                      legDB Ole   gDBOle                                    
        gDBO                      legDBOlegD  BOleg                         DBOlegDBO   
       legDB                      OlegDBOle  gDBOl                        egDBOlegDBOl  
       egDBO                     legDBOlegD BOleg                       DBOleg    DBOl  
       egDBO                     legDBOleg  DBOle                     gDBOleg    DBOle  
       gDBOl                    egDBOlegD  BOlegD                   BOlegDB     OlegD   
       BOleg                    DBOlegDB   OlegDBOlegDBOlegDBOl   egDBOle     gDBOl     
        egDB                   OlegDBOl    egDBOlegDBOlegDBOlegDBOlegDB      OlegD      
        BOle                   gDBOleg     DBOle   gDBOl   egDBOlegDB      OlegDB       
        Oleg                  DBOlegDB      Ole   gDBOlegDBOlegDBOl      egDBOl         
        egDBO               legDB OlegD         BOlegDBOlegDBOlegD     BOlegDB          
         Oleg             DBOle  gDBOleg         DBOlegDBOlegDBOlegD   BOlegDBO         
         legDB            OlegDBOlegDBOl                     egDBOleg    DBOlegDBO      
          legDB            OlegDBOlegDB              Oleg       DBOleg  DBOl egDBO      
          legDBO              legD                   BOle        gDBOle  gDBOlegD       
           BOlegD                                BOl              egDBO    legD         
            BOlegDBO                            legD              BOleg     DBOl        
               egDBOle                          gDBO              legDBOlegDBOle        
     gDB        OlegDBOleg                       DBOl           egDBOlegDBOlegD         
    BOlegDB    OlegDBOlegDBOlegD                  BOl         egDBOle    g              
    DBOlegDBOlegDB OlegDBOlegDBOlegDBOle           gDBO    legDBOl                      
    egDB OlegDBOlegDBOl    egDBOlegDBOlegD BOlegDBOlegDBOlegDBOl                        
     egDB  OlegDBOleg         DBOlegDBOle gDBOlegDBOlegDBOleg                           
      DBOl   egDBOl         egDBOlegDBOl egDBO legDBOlegDB                              
       OlegDBOleg           DBOlegDBOle  gDBO                                           
        legDBOl              egDBOleg   DBOl                                            
          egD                BOlegD    BOle                                             
                              gDBOle  gDBO                                              
                               legDBOlegD                                               
                                 BOlegDB                                                
                                   Ole                      
```

**Comment by qpfiffer** [comment]
:checkered_flag:

**Comment by dequis** [comment]
@Xe: Your suggested change has several issues that don't follow the [PSR-1 Basic Coding Standard][psr-1]:

 * Section 2.3: "Files SHOULD either declare symbols (classes, functions, constants, etc.) or cause side-effects (e.g. generate output, change .ini settings, etc.) but SHOULD NOT do both"
 * Section 3: "Namespaces and classes MUST follow an 'autoloading' PSR"

Additionally, from [PSR-2 Coding Style Guide][psr-2]:

* Opening braces for classes MUST go on the next line, and closing braces MUST go on the next line after the body

[psr-1]: https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-1-basic-coding-standard.md
[psr-2]: https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-2-coding-style-guide.md

**Comment by kyleterry** [comment]
we need to do a few things here:

- Please make sure async.c is acutlaly syunc with a sprinkle of a.
- disallow all authentic shit-posting™ in all reference comments and selected sections that transcribe conversation related to cbusiness proposals.
- if a rock is found, you should return it immediately.
- tell me the truth about steel beams.
- steel beams 
- make sure doublemarked established democracy in ukraine.
- if I am found dead, plz don't let cats eat.
- async == GIVE UP
- dogs keep pooping in the yard.
- safari is a pile of shitt
-

**Comment by colby** [comment]
Could confirm, safari is a steel beam.

**Comment by cmevident** [comment]
10866274_10204874634798069_1461645443751339010_o
@kyleterry slow down shitlord

**Comment by kyleterry** [comment]
@cmevident I agree, shitlord considered harmful

**Comment by trinque** [comment]
Guys, it's important to stay on top of pull requests. You want to make the community feel engaged.

**Comment by kyleterry** [comment]
oh fuck.

**Comment by dequis** [comment]
b-but he didn't fix the style issues

**Comment by kyleterry** [comment]
:shipit: :package:

**Comment by benwaffle** [comment]
ayy lmao

**Comment by qpfiffer** [comment]
Remember when we knew how to have fun

**Comment by lykkin** [comment]
no

**Comment by kyleterry** [comment]
something happened to america

**Comment by trinque** [comment]
✈ ▌▌

**Comment by trinque** [comment]
never forget

**Comment by kyleterry** [comment]
jet fuel can't derp steel beams

**Comment by qpfiffer** [comment]
:package: :japanese_ogre:

**Comment by mission712** [comment]
......

**Comment by qpfiffer** [comment]
Oh, good. :package: :package: :package:

**Comment by lykkin** [comment]
:package:

**Comment by dequis** [comment]
:package:

**Comment by Xe** [comment]
:package: :shipit:

**Comment by colby** [comment]
GROSS

**Comment by lykkin** [comment]
thx @Xe 

u da real mvp

**Comment by mission712** [comment]
+1 to this PR. Should definitely be added. :+1: :+1: :+1: 
:white_large_square: :white_large_square: :white_large_square: :white_large_square: :white_large_square: :white_large_square: :white_large_square: :white_large_square: :white_large_square:
:white_large_square: :white_large_square: :white_large_square: :package: :package: :package: :package: :package: :white_large_square:
:white_large_square: :white_large_square: :package: :white_large_square: :white_large_square: :white_large_square: :package: :package: :white_large_square:
:white_large_square: :package: :package: :package: :package: :package: :white_large_square: :package:  :white_large_square:
:white_large_square: :package: :white_large_square: :white_large_square: :white_large_square: :package: :white_large_square: :package: :white_large_square:
:white_large_square: :package: :white_large_square: :white_large_square: :white_large_square: :package: :white_large_square: :package: :white_large_square:
:white_large_square: :package: :white_large_square: :white_large_square: :white_large_square: :package: :package: :white_large_square: :white_large_square:
:white_large_square: :package: :package: :package: :package: :package: :white_large_square: :white_large_square:  :white_large_square:
:white_large_square: :white_large_square: :white_large_square: :white_large_square: :white_large_square: :white_large_square: :white_large_square: :white_large_square: :white_large_square:

**Comment by Aleph0x** [comment]
Screenshot 2026-03-21 185100
[
Screenshot 2026-03-21 185032
](url)

**Comment by dequis** [comment]
📦

**Pull request merged**
