### PR TITLE
add more redundancy

### PR DESCRIPTION
**Pull request by skyhighwings**
I went through this project and I didn't see enough redundancy, so I added some read-write redundancy so this project is more webscale and cloud-friendly.

### CODE REVIEW

**Comment by morenoh149** [comment]
🔪✊

**Comment by skyhighwings** [comment]
I was told to ping @qpfiffer for quick review. Is this cloudscale enough for this project?

**Comment by skyhighwings** [comment]
And you too @Xe.

**Comment by qpfiffer** [comment]
This conflicts with my religion.

**Pull request closed without merging**
