### PR TITLE
improves brand identity conveyed in aol.c

### PR DESCRIPTION
**Pull request by trinque**

### CODE REVIEW

**Comment by dequis** [comment]
:+1:

**Comment by kyleterry** [comment]
:shipit:

**Comment by Xe** [comment]
:package: :boom"

**Comment by Xe** [comment]
```
/*   YOU HAVE BEEN VISITED BY THE SCAREY    
 *   PULL MONSTER! IF YOU DO NOT PULL       
 *   REQUEST THIS ONTO 10 MORE REPO'S,      
 *   THE SCAREY PULL MONSTER WILL INSTALL   
 *   NON FREE (AS IN NON FREE) SOFTWARE     
 *   ON YOUR COMPTER!!!!!!!                 
*/


                                           .""--.._                
                                           []      `'--.._         
                                           ||__           `'-,     
                                         `)||_ ```'--..       \    
                     _                    /|//}        ``--._  |   
                  .'` `'.                /////}              `\/   
                 /  .""".\              //{///                     
                /  /_  _`\\            // `||                      
               SCAREY PULL!!!        _//   ||                      
                | |  /\  )|        _///\   ||                      
                | |L====J |       / |/ |   ||                      
               /  /'-..-' /    .'`  \  |   ||                      
              /   |  :: | |_.-`      |  \  ||                      
             /|   `\-::.| |          \   | ||                      
           /` `|   /    | |          |   / ||                      
         |`    \   |    / /          \  |  ||                      
        |       `\_|    |/      ,.__. \ |  ||                      
        /                     /`    `\ ||  ||                      
       |           .         /        \||  ||                      
       |                     |         |/  ||                      
       /         /           |         (   ||                      
      /          .           /          )  ||                      
     |            \          |             ||                      
    /             |          /             ||                      
   |\            /          |              ||                      
   \ `-._       |           /              ||                      
    \ ,//`\    /`           |              ||                      
     ///\  \  |             \              ||                      
    |||| ) |__/             |              ||                      
    |||| `.(                |              ||                      
    `\\` /`                 /              ||                      
       /`                   /              ||                      
 jgs  /                     |              ||                      
     |                      \              ||                      
    /                        |             ||                      
  /`                          \            ||                      
/`                            |            ||                      
`-.___,-.      .-.        ___,'            ||                      
         `---'`   `'----'`                       
```

**Comment by qpfiffer** [comment]
Thanks @colby

**Comment by qpfiffer** [comment]
:banana:

**Comment by dequis** [comment]
:package:

**Pull request merged**
